export const SZTFR = {
  API_PATH: "https://us-central1-sztfr-7a759.cloudfunctions.net",
  LOCAL_STORAGE_LOG_IN_EMAIL: "LOCAL_STORAGE_LOG_IN_EMAIL",
  FIREBASE_RESPONSE: "FIREBASE_RESPONSE",
  FIREBASE_SUCCESS: "FIREBASE_SUCCESS",
  FIREBASE_ERROR: "FIREBASE_ERROR",
};
