export const SZTFR = {
  LOCAL_STORAGE_LOG_IN_EMAIL: "LOCAL_STORAGE_LOG_IN_EMAIL",
  FIREBASE_RESPONSE: "FIREBASE_RESPONSE",
  FIREBASE_SUCCESS: "FIREBASE_SUCCESS",
  FIREBASE_ERROR: "FIREBASE_ERROR",
};
